// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Saveフォルダ標準化","status":true,"description":"Saveフォルダ標準化プラグイン","parameters":{}},
{"name":"KNS_MessageExport","status":false,"description":"[ver.1.0.0(2022/3/23)]exports texts in events and database.","parameters":{}},
{"name":"KNS_MessageImport","status":false,"description":"[ver.1.0.0(2022/3/23)]Merges .txt files as .json database exported by KNS_MessageExport","parameters":{}},
{"name":"ReplaceFileName","status":false,"description":"画像、音声、動画読み込み時、指定された名前を任意の名前に置き換えて読み込むようにします。","parameters":{}}
];
